function createfigure(X1, Y1, X2, Y2)
%CREATEFIGURE(X1, Y1, X2, Y2)
%  X1:  vector of x data
%  Y1:  vector of y data
%  X2:  vector of x data
%  Y2:  vector of y data

%  Auto-generated by MATLAB on 21-Feb-2019 23:10:55

% Create figure
figure1 = figure('InvertHardcopy','off','Color',[1 1 1]);

% Create axes
axes1 = axes('Parent',figure1,...
    'Position',[0.113782051282051 0.153532608695652 0.786858974358974 0.645380434782609]);
hold(axes1,'on');

% Create plot
plot(X1,Y1,'DisplayName','\phi imu','LineWidth',2);

% Create plot
plot(X2,Y2,'DisplayName','\phi cmd','LineWidth',2,'LineStyle','--');

% Create xlabel
xlabel('time [sec]','FontSize',24);

% Create ylabel
ylabel('roll [rad]','FontSize',24);

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0 45]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[-0.4 0.4]);
% Uncomment the following line to preserve the Z-limits of the axes
% zlim(axes1,[-1 1]);
box(axes1,'on');
grid(axes1,'on');
% Set the remaining axes properties
set(axes1,'FontSize',24.2277407631738);
% Create legend
legend1 = legend(axes1,'show');
set(legend1,...
    'Position',[0.787393164542364 0.699954720902378 0.112980767081563 0.0985054320291332],...
    'FontSize',21.8049666868564);

